name: Rust ARM Cross Compiling

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y -qq gcc-arm-linux-gnueabihf && rustup target add armv7-unknown-linux-gnueabihf
    - name: Build
      run: cargo build --target=armv7-unknown-linux-gnueabihf --verbose
    - name: Run tests
      run: cargo test --target=armv7-unknown-linux-gnueabihf --verbose

